# Generated by Django 5.2.3 on 2025-06-24 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_category_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e ora di creazione del record",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora dell'ultima modifica del record",
                    ),
                ),
                ("cart_id", models.CharField(blank=True, max_length=250)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aperto"),
                            ("completed", "Completato"),
                            ("cancelled", "Annullato"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Stato corrente del carrello",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utente proprietario del carrello",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e ora di creazione del record",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora dell'ultima modifica del record",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantità richiesta, minimo 1",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prezzo unitario al momento dell'aggiunta",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="Carrello di appartenenza",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Prodotto aggiunto al carrello",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voce Carrello",
                "verbose_name_plural": "Voci Carrello",
                "ordering": ["-created_at"],
                "unique_together": {("cart", "product")},
            },
        ),
    ]
