# Generated by Django 5.2.3 on 2025-07-09 10:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
        ("products", "0004_product_discount_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "CartItem",
                "verbose_name_plural": "CartItems",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time of record creation"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="open",
                help_text="current status of the cart",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time of last record update"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                help_text="Cart of which this item is part",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date and time of record creation"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                help_text="Product associated with this cart item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="minimum quantity is 1, default is 1",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="unit price of the product at the time of adding to cart",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date and time of last record update"
            ),
        ),
    ]
