# Generated by Django 5.2.3 on 2025-06-24 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Quantità richiesta, minimo 1",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
