# Generated by Django 5.2.3 on 2025-07-07 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_end_date",
            field=models.DateTimeField(
                blank=True, help_text="End date of the current discount ", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage of discount applied to the product (0-100%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_start_date",
            field=models.DateTimeField(
                blank=True, help_text="Start date of the current discount", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_discount_active",
            field=models.BooleanField(
                default=False, help_text="Activate/deactivate the current discount"
            ),
        ),
    ]
